# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/wily64"
    config.vm.hostname = "ubuntu"
    config.vm.define "ubuntu" do |ubuntu|
    end

    config.vm.network "public_network", bridge: 'wlan0'

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.ssh.forward_agent = false
    config.ssh.forward_x11 = false

    config.vm.provider "virtualbox"
    config.vm.provider :virtualbox do |vbox|
        vbox.gui = true
        vbox.name = "ubuntu"
        vbox.customize ["modifyvm", :id, "--memory", "1024"]
        vbox.customize ["modifyvm", :id, "--ioapic", "on"]
        vbox.customize ["modifyvm", :id, "--cpus", "2"]
        vbox.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
        vbox.customize ["modifyvm", :id, "--hwvirtex", "on"]
        vbox.customize ["modifyvm", :id, "--pae", "on"]
        vbox.customize ["modifyvm", :id, "--audio", "none"]
        vbox.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vbox.customize ["modifyvm", :id, "--nictype2", "virtio"]
        vbox.linked_clone = true if Vagrant::VERSION =~ /^1.8/
    end

    config.vm.provision "shell", inline: <<-SHELL
        set -eux
        apt-get update
        apt-get install -y virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
        apt-get install -y language-pack-pl
        apt-get install -y tmux zsh vim
        apt-get install -y mate-desktop-environment slim xorg
        service slim start
    SHELL
end
