# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/wily64"
    config.vm.network "public_network", bridge: 'wlan0'

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.ssh.forward_agent = false
    config.ssh.forward_x11 = false

    config.vm.provider "virtualbox"
    config.vm.provider :virtualbox do |vbox|
        vbox.gui = true
        vbox.customize ['modifyvm', :id, '--memory', '2048']
        vbox.customize ["modifyvm", :id, "--ioapic", "on"]
        vbox.customize ["modifyvm", :id, "--cpus", "2"]
        vbox.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
        vbox.customize ["modifyvm", :id, "--hwvirtex", "on"]
        vbox.customize ["modifyvm", :id, "--pae", "on"]
        vbox.customize ["modifyvm", :id, "--audio", "none"]
        vbox.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vbox.customize ["modifyvm", :id, "--nictype2", "virtio"]
        vbox.customize ['modifyvm', :id, '--usb', 'on']
        vbox.customize ['modifyvm', :id, '--usbehci', 'on']
        vbox.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'CHIP',                              '--vendorid', '0x1F3A']
        vbox.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'CHIP in fastboot mode',             '--vendorid', '0x18d1', '--product', '0x1010']
        vbox.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'CHIP Linux Gadget USB Serial Port', '--vendorid', '0x0525', '--product', '0xA4A7']
        vbox.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'PL2303 Serial Port',                '--vendorid', '0x067b', '--product', '0x2303']
        vbox.linked_clone = true if Vagrant::VERSION =~ /^1.8/
    end

    config.vm.provision "shell", inline: <<-SHELL
        set -eux
        apt-get update
        apt-get install -y virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
        apt-get install -y language-pack-pl
        apt-get install -y mate-desktop-environment slim xorg
        apt-get install -y chromium-browser
        usermod -a -G dialout vagrant
        usermod -a -G plugdev vagrant
        echo -e 'SUBSYSTEM=="usb", ATTRS{idVendor}=="1f3a", ATTRS{idProduct}=="efe8", GROUP="plugdev", MODE="0660" SYMLINK+="usb-chip"
        SUBSYSTEM=="usb", ATTRS{idVendor}=="18d1", ATTRS{idProduct}=="1010", GROUP="plugdev", MODE="0660" SYMLINK+="usb-chip-fastboot"
        SUBSYSTEM=="usb", ATTRS{idVendor}=="1f3a", ATTRS{idProduct}=="1010", GROUP="plugdev", MODE="0660" SYMLINK+="usb-chip-fastboot"
        SUBSYSTEM=="usb", ATTRS{idVendor}=="067b", ATTRS{idProduct}=="2303", GROUP="plugdev", MODE="0660" SYMLINK+="usb-serial-adapter"
        ' | tee /etc/udev/rules.d/99-allwinner.rules
        udevadm control --reload-rules
        sed -i 's/.*default_user.*/default_user vagrant/g' /etc/slim.conf
        sed -i 's/.*auto_login.*/auto_login yes/g' /etc/slim.conf
        service slim start
    SHELL
end
