VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.guest = :freebsd
    config.vm.box = "freebsd/FreeBSD-10.2-RELEASE"

    config.vm.base_mac = "0A306032060E"
    config.vm.network "private_network", ip: "10.0.1.10"

    config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

    config.ssh.forward_agent = false
    config.ssh.forward_x11 = false
    config.ssh.shell = "sh"

    config.vm.provider "virtualbox"
    config.vm.provider :virtualbox do |vbox|
        vbox.gui = true
        vbox.customize ["modifyvm", :id, "--memory", "1024"]
        vbox.customize ["modifyvm", :id, "--ioapic", "on"]
        vbox.customize ["modifyvm", :id, "--cpus", "2"]
        vbox.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
        vbox.customize ["modifyvm", :id, "--hwvirtex", "on"]
        vbox.customize ["modifyvm", :id, "--pae", "on"]
        vbox.customize ["modifyvm", :id, "--audio", "none"]
        vbox.linked_clone = true if Vagrant::VERSION =~ /^1.8/
    end

    config.vm.provision "shell", inline: <<-SHELL
        set -eux
        env ASSUME_ALWAYS_YES=YES pkg bootstrap
        env ASSUME_ALWAYS_YES=YES pkg update -f
        pkg install -y xorg-server xinit xauth xscreensaver xf86-input-keyboard xf86-input-mouse
        echo 'hald_enable="YES"' >> /etc/rc.conf
        echo 'dbus_enable="YES"' >> /etc/rc.conf
        pkg install -y virtualbox-ose-additions
        echo 'vboxguest_enable="YES"' >> /etc/rc.conf
        echo 'vboxservice_enable="YES"' >> /etc/rc.conf
        pkg install -y tmux zsh vim sudo
        pkg install -y mate-desktop mate slim xorg
        echo 'slim_enable="YES"' >> /etc/rc.conf
        echo 'exec mate-session' > /home/vagrant/.xinitrc
        chown vagrant /home/vagrant/.xinitrc
        service slim start
    SHELL
end
